### ISSUE TITLE
why.

### ISSUE THREAD

**Issue by ghost** [code4lives/code4lives#1]
why

**Comment by rockstarrudy** [comment]
@LankyBox01 well aboutdavid canceled the other group. so - made A new group! I was wondering if you wanted to join.

**Comment by rockstarrudy** [comment]
@LankyBox01 would you like to join?

**Comment by ghost** [comment]
> @LankyBox01 would you like to join?

Fine, i will join

**Comment by ghost** [comment]
One one condition: Make an account here vhttps://techhelp.flarum.cloud/

**Comment by rockstarrudy** [comment]
@LankyBox01 I will but why?

**Comment by rockstarrudy** [comment]
@LankyBox01 also can you ask others to join this group!

**Comment by ghost** [comment]
> @LankyBox01 I will but why?

Because no one is using it and no one likes it :(

> @LankyBox01 also can you ask others to join this group!

You also have to ask others to join the forum

**Comment by rockstarrudy** [comment]
@LankyBox01 hmm why? this is beacuse of covid not becuse of people who want to join the forum

**Comment by rockstarrudy** [comment]
@LankyBox01 check my tech forum

https://coders.flarum.cloud

**Comment by rockstarrudy** [comment]
@LankyBox01 I can make you mod in it and it has some people

**Comment by rockstarrudy** [comment]
>> @LankyBox01 also can you ask others to join this group!

>You also have to ask others to join the forum

@LankyBox01 ok I will try! but you have to also ask!

**Comment by ghost** [comment]
> @LankyBox01 hmm why? this is beacuse of covid not becuse of people who want to join the forum

It's not about this group, make an account and tell other people to join my forum!

**Comment by rockstarrudy** [comment]
@LankyBox01 okay but you also have to ask about joining this group!!!!!!

**Comment by ghost** [comment]
> @LankyBox01 okay but you also have to ask about joining this group!!!!!!

yes

**Comment by rockstarrudy** [comment]
@LankyBox01 but isnt this like trading. asking people to join the forum

**Comment by ghost** [comment]
> @LankyBox01 but isnt this like trading. asking people to join the forum

it is kind of.

**Comment by rockstarrudy** [comment]
doesn't this feel like cheating? and why do you need to make a forum? just curious @LankyBox01

**Comment by rockstarrudy** [comment]
@LankyBox01 I have tried to make a coding forum and it failed

**Comment by rockstarrudy** [comment]
@LankyBox01 only make a forum if you have multiple people backing it up

**Comment by rockstarrudy** [comment]
@LankyBox01 but whatever

**Comment by ghost** [comment]
> @LankyBox01 only make a forum if you have multiple people backing it up

Now i have 2, and you have 1 :)

**Comment by rockstarrudy** [comment]
@LankyBox01 lets ask people then!

**Comment by rockstarrudy** [comment]
@LankyBox01 if you get one person to join I will join the forum! ok?

**Comment by ghost** [comment]
> @LankyBox01 if you get one person to join I will join the forum! ok?

does myself count?

**Comment by rockstarrudy** [comment]
@LankyBox01 hahah not really. 😜 

beacuse I already joined your forum so its 1v1

**Comment by ghost** [comment]
https://github.com/code4lives/code4lives/pull/2
Accept it

**Comment by rockstarrudy** [comment]
@LankyBox01 wait

**Comment by rockstarrudy** [comment]
@LankyBox01 can I bee a mod/admin!

**Comment by ghost** [comment]
> @LankyBox01 can I bee a mod/admin!

what's your username?

**Comment by rockstarrudy** [comment]
@LankyBox01 brb

**Comment by rockstarrudy** [comment]
@LankyBox01 its called dude

**Comment by ghost** [comment]
> @LankyBox01 its called dude

https://techhelp.flarum.cloud/u/codersunited

**Comment by rockstarrudy** [comment]
@LankyBox01 can you use the users directy extensions

**Comment by ghost** [comment]
> @LankyBox01 can you use the users directy extensions

what?

**Comment by rockstarrudy** [comment]
@LankyBox01 can I be full admin for a sec

**Comment by ghost** [comment]
I can see your email, you're using yandex.
What extensions do you want? I'll add them

**Comment by rockstarrudy** [comment]
@LankyBox01 can you  not look at the email

**Comment by rockstarrudy** [comment]
@LankyBox01 it feels like a privacy invasion

**Comment by ghost** [comment]
> @LankyBox01 it feels like a privacy invasion

fine. you know i won't do anything with it right?

**Comment by rockstarrudy** [comment]
yeah

**Comment by ghost** [comment]
> yeah

Ok,
What extensions do you want? I'll add them

**Comment by rockstarrudy** [comment]
@LankyBox01 can I just be admin?

**Comment by rockstarrudy** [comment]
@LankyBox01 install the user directory extension

**Comment by ghost** [comment]
> @LankyBox01 install the user directory extension

done, happy?

**Comment by rockstarrudy** [comment]
@LankyBox01 yeah but can I have permission for the admin panel

**Comment by rockstarrudy** [comment]
@LankyBox01 I dont see the user directory panel

**Comment by ghost** [comment]
> @LankyBox01 yeah but can I have permission for the admin panel

Why?

**Comment by rockstarrudy** [comment]
@LankyBox01 nvm

**Comment by rockstarrudy** [comment]
@LankyBox01 because you dont know how to properly do the user directory extension

**Comment by rockstarrudy** [comment]
@LankyBox01 and I can make better tags!

**Comment by ghost** [comment]
> @LankyBox01 and I can make better tags!

tell me those.

**Comment by rockstarrudy** [comment]
@LankyBox01 its easier if Im admin, and I just need it for 5 mins

**Comment by ghost** [comment]
> @LankyBox01 its easier if Im admin, and I just need it for 5 mins

We consider publicizing the administration panel a security risk, you already did some mess.
Demoted temporarily

**Comment by rockstarrudy** [comment]
What mess? @LankyBox01

**Comment by rockstarrudy** [comment]
@LankyBox01 I never broke the guides rule!!

**Comment by ghost** [comment]
You removed the tags, which **i purposely added**, and you also restored a deleted post.
Please don't undo moderator actions

**Comment by rockstarrudy** [comment]
@LankyBox01 well those tags are irrelevant anyways

**Comment by ghost** [comment]
No they're not. wait until i promote you to co-admin just be patient

**Comment by rockstarrudy** [comment]
@LankyBox01 ok

**Comment by rockstarrudy** [comment]
@LankyBox01 u didn't even setup private discussions 😄

**Comment by ghost** [comment]
> @LankyBox01 u didn't even setup private discussions 😄

i did.

**Comment by rockstarrudy** [comment]
@LankyBox01 well you made that only admins can start them.

**Comment by rockstarrudy** [comment]
@LankyBox01 this why I wanna help

**Comment by ghost** [comment]
> @LankyBox01 well you made that only admins can start them.

I made them temporarily.

**Comment by rockstarrudy** [comment]
@LankyBox01 hmm ok

**Comment by rockstarrudy** [comment]
@LankyBox01 can I plz be admin, beacuse of the settings I cant even edit my post lol!

**Comment by rockstarrudy** [comment]
@LankyBox01 why u delete my post?

**Comment by rockstarrudy** [comment]
@LankyBox01 now we have been working on your forum! now can you get one person in this group!

**Comment by ghost** [comment]
Ok, you've been promoted to supervisor, here's what you can do:
- Lock discussions
- Edit posts
- Access the reports queue
- Have access to the admin panel (kind-of)

**Comment by ghost** [comment]
> @LankyBox01 now we have been working on your forum! now can you get one person in this group!

I entered your forum, you entered my forum.

That's an equal deal

**Comment by rockstarrudy** [comment]
@LankyBox01 that wasn't the deal

**Comment by rockstarrudy** [comment]
@LankyBox01 u didn't have to join my forum

**Comment by ghost** [comment]
> @LankyBox01 that wasn't the deal

yes it was.

**Comment by rockstarrudy** [comment]
@LankyBox01 you had to get someone to join the group

**Comment by rockstarrudy** [comment]
@LankyBox01 I can delete your account if u want so the deal is still on

**Comment by ghost** [comment]
No. that means you're tricking me

**Comment by rockstarrudy** [comment]
@LankyBox01 hmm, let me give u proof

**Comment by ghost** [comment]
stop. the deal we've made is enoughly equal

**Comment by rockstarrudy** [comment]
@LankyBox01 really. we can always undo a deal

**Comment by ghost** [comment]
> @LankyBox01 really. we can always undo a deal

no, leave it how it is.

> I entered your forum, you entered my forum.

**Comment by rockstarrudy** [comment]
![Screen Shot 2020-09-01 at 9 24 34 AM](https://user-images.githubusercontent.com/68394233/91856772-02a4d480-ec35-11ea-95b3-bba7bfcbc2ee.png)

**Comment by rockstarrudy** [comment]
@LankyBox01 there was a mis understanding in the deal

**Comment by ghost** [comment]
That actually isn't really a fair deal.

**Comment by rockstarrudy** [comment]
@LankyBox01 joining my forum is something totally different. I never even asked you to join it.

**Comment by rockstarrudy** [comment]
@LankyBox01  well I never said to join the forum and you never said you will

**Comment by rockstarrudy** [comment]
@LankyBox01 to make the deal fair again I can delete your forum account

**Comment by rockstarrudy** [comment]
@LankyBox01 always that forum is never active I was just showing it to u

**Comment by ghost** [comment]
> @LankyBox01 to make the deal fair again I can delete your forum account

and then i don't have to do anything?

**Comment by rockstarrudy** [comment]
@LankyBox01 well you have to try to get one person in this group.

**Comment by rockstarrudy** [comment]
@LankyBox01 or...
I have an idea

**Comment by rockstarrudy** [comment]
what if you make a post about code4lives in the forum. its counts as adding someone beacuse your advertising it!

**Comment by ghost** [comment]
#2
Accept it

**Comment by rockstarrudy** [comment]
@LankyBox01 did it

**Comment by rockstarrudy** [comment]
@LankyBox01 your breaking the deal big time

**Comment by rockstarrudy** [comment]
@LankyBox01 this deal is so confusing, I might just quit the deal
