### ISSUE TITLE
hey lankybox01 (yeetoburro1)

### ISSUE THREAD

**Issue by ghost** [code4lives/code4lives#3]
Is it true you got permabanned? If so, why? BTW, you got discord?

**Comment by ghost** [comment]
You're Yeetoburro1?
Yes, i got banned for sharing a link to github (a userscript).
And yes, i got discord.

**Comment by LankyBox01** [comment]
![account_blocked](http://u.cubeupload.com/LankyBox01/6MtaOD.png)

**Comment by LankyBox01** [comment]
https://forums.scratchstats.com/topic/435189/ < Where it happened

**Comment by grixcloud** [comment]
@Letzdotheodeyssey would you like to join the group?

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey would you like to join the team?

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey did you know that @LankyBox01 is on the team

**Comment by ghost** [comment]
> You're Yeetoburro1?
> Yes, i got banned for sharing a link to github (a userscript).
> And yes, i got discord.

Oof. Wanna join my server?

**Comment by ghost** [comment]
> @Letzdotheodeyssey did you know that @LankyBox01 is on the team

I kinda want to joun (Ik that lanky was on the team, thats why I posted lol)

**Comment by rockstarrudy** [comment]
Okay ! I will add you to the team the. Check your email for a invite

**Comment by ghost** [comment]
Why did you close? Im still waiting for lankybox's response

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey response for what?

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey 
do that:

> Okay ! I will add you to the team the. Check your email for a invite

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey tell me wen u join the orgiszantion

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey what coding langs do u know

**Comment by ghost** [comment]
Done. Im waiting for lankybox to reply with his discord stuff.

**Comment by ghost** [comment]
I know Python and scratch. (Yes, scratch is a little lame)

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey do u know html and css?

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey um lankybox said his parents dont allow him discord.

**Comment by ghost** [comment]
Oh okay. Rip that. And no, I do not know CSS or HTML. Lanky, anyplace I can contact other than here?

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey you can use a fourm:


https://coders.flarum.cloud

**Comment by rockstarrudy** [comment]
@Letzdotheodeyssey it says that you didnt accept the invite
